---
functional:
  - Сайт должен представить возможность двум игрокам соревноваться друг с другом в решении задач
  - Игроки должны видеть написание кода друг у друга в режиме онлайн
  - Пользователи должны иметь возможность регистрации и авторизации
  - Пользователи могут создавать игры
  - Пользователь может подключаться к игре с другим пользователем
  - Пользователь может создавать игру с ботом
  - Пользователь может проверить решение своей задачи
  - Проверка решения своей задачи пользователем может выполняться неограниченное количество раз
  - Игра пока может длиться неограниченное время либо заданное создателем игры
  - Пользователь может переподключиться к игре в любое время
  - Пользователь может сдаться во время выполнения игры
  - Пользователь может видеть обратный отсчет до завершения игры
  - После завершения игры пользователь может провести повторный матч с соперником
  - Пользователи могут общаться в чате друг с другом
  - Пользователь может выбрать язык задачи
  - Пользователь может посмотреть результат выполнения проверок
  - Пользователь может выбрать язык программирования для выполнения задачи
  - Пользователь может сбросить решение задачи
  - Пользователь может просмотреть описание задачи в отдельном окне
  - Пользователь может видеть список игр для присоединения
  - Пользователь может посмотреть историю проведенных игр
  - Пользователь может посмотреть рейтинг других игроков за месяц, неделю или все время
  - При истечении времени отсчета игра завершается без победителей
  - При создании игры можно выбрать уровень сложности
  - При создании игры можно выбрать игру с другом
  - При создании игры можно выбрать случайную задачу либо конкретную
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Если соперник сдался, победа присуждается второму участнику
  - Игра начинается после подключения двух игроков